ERROR - 2024-08-25 00:10:35 --> Error connecting to the database: mysqli_sql_exception: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\presupuesto\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\presupuesto\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', '', Object(SensitiveParameterValue), '', 3306, '', 0)
#1 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\presupuesto\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\presupuesto\system\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\presupuesto\app\Models\UsuarioModel.php(29): CodeIgniter\Model->__call('get', Array)
#6 C:\xampp\htdocs\presupuesto\app\Controllers\UsuarioController.php(22): App\Models\UsuarioModel->obtener(Array)
#7 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(933): App\Controllers\UsuarioController->login()
#8 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#9 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\presupuesto\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\presupuesto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\presupuesto\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user ''@'localhost' (using password: NO) in C:\xampp\htdocs\presupuesto\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\presupuesto\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\presupuesto\system\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\presupuesto\app\Models\UsuarioModel.php(29): CodeIgniter\Model->__call('get', Array)
#5 C:\xampp\htdocs\presupuesto\app\Controllers\UsuarioController.php(22): App\Models\UsuarioModel->obtener(Array)
#6 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(933): App\Controllers\UsuarioController->login()
#7 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#8 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\presupuesto\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\presupuesto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\presupuesto\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-08-25 00:10:35 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
[Method: POST, Route: loguear]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuario`
WHERE `email` = :email:', [...], false)
 3 SYSTEMPATH\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Models\UsuarioModel.php(29): CodeIgniter\Model->__call('get', [])
 5 APPPATH\Controllers\UsuarioController.php(22): App\Models\UsuarioModel->obtener([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->login()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-25 00:11:55 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'localhost' in C:\xampp\htdocs\presupuesto\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\presupuesto\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'localhost', 3306, '', 0)
#1 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\presupuesto\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\presupuesto\system\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\presupuesto\app\Models\UsuarioModel.php(29): CodeIgniter\Model->__call('get', Array)
#6 C:\xampp\htdocs\presupuesto\app\Controllers\UsuarioController.php(22): App\Models\UsuarioModel->obtener(Array)
#7 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(933): App\Controllers\UsuarioController->login()
#8 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#9 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\presupuesto\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\presupuesto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\presupuesto\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'localhost' in C:\xampp\htdocs\presupuesto\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\presupuesto\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\presupuesto\system\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\presupuesto\app\Models\UsuarioModel.php(29): CodeIgniter\Model->__call('get', Array)
#5 C:\xampp\htdocs\presupuesto\app\Controllers\UsuarioController.php(22): App\Models\UsuarioModel->obtener(Array)
#6 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(933): App\Controllers\UsuarioController->login()
#7 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#8 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\presupuesto\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\presupuesto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\presupuesto\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-08-25 00:11:55 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'localhost'
[Method: POST, Route: loguear]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuario`
WHERE `email` = :email:', [...], false)
 3 SYSTEMPATH\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Models\UsuarioModel.php(29): CodeIgniter\Model->__call('get', [])
 5 APPPATH\Controllers\UsuarioController.php(22): App\Models\UsuarioModel->obtener([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->login()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-25 00:12:00 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'localhost' in C:\xampp\htdocs\presupuesto\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\presupuesto\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'localhost', 3306, '', 0)
#1 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\presupuesto\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\presupuesto\system\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\presupuesto\app\Models\UsuarioModel.php(29): CodeIgniter\Model->__call('get', Array)
#6 C:\xampp\htdocs\presupuesto\app\Controllers\UsuarioController.php(22): App\Models\UsuarioModel->obtener(Array)
#7 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(933): App\Controllers\UsuarioController->login()
#8 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#9 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\presupuesto\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\presupuesto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\presupuesto\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'localhost' in C:\xampp\htdocs\presupuesto\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\presupuesto\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\presupuesto\system\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\presupuesto\app\Models\UsuarioModel.php(29): CodeIgniter\Model->__call('get', Array)
#5 C:\xampp\htdocs\presupuesto\app\Controllers\UsuarioController.php(22): App\Models\UsuarioModel->obtener(Array)
#6 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(933): App\Controllers\UsuarioController->login()
#7 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#8 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\presupuesto\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\presupuesto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\presupuesto\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-08-25 00:12:00 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'localhost'
[Method: POST, Route: loguear]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuario`
WHERE `email` = :email:', [...], false)
 3 SYSTEMPATH\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Models\UsuarioModel.php(29): CodeIgniter\Model->__call('get', [])
 5 APPPATH\Controllers\UsuarioController.php(22): App\Models\UsuarioModel->obtener([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->login()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-25 00:12:10 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'localhost' in C:\xampp\htdocs\presupuesto\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\presupuesto\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'localhost', 3306, '', 0)
#1 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\presupuesto\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\presupuesto\system\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\presupuesto\app\Models\UsuarioModel.php(29): CodeIgniter\Model->__call('get', Array)
#6 C:\xampp\htdocs\presupuesto\app\Controllers\UsuarioController.php(22): App\Models\UsuarioModel->obtener(Array)
#7 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(933): App\Controllers\UsuarioController->login()
#8 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#9 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\presupuesto\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\presupuesto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\presupuesto\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'localhost' in C:\xampp\htdocs\presupuesto\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\presupuesto\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\presupuesto\system\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\presupuesto\app\Models\UsuarioModel.php(29): CodeIgniter\Model->__call('get', Array)
#5 C:\xampp\htdocs\presupuesto\app\Controllers\UsuarioController.php(22): App\Models\UsuarioModel->obtener(Array)
#6 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(933): App\Controllers\UsuarioController->login()
#7 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#8 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\presupuesto\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\presupuesto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\presupuesto\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-08-25 00:12:10 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'localhost'
[Method: POST, Route: loguear]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuario`
WHERE `email` = :email:', [...], false)
 3 SYSTEMPATH\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Models\UsuarioModel.php(29): CodeIgniter\Model->__call('get', [])
 5 APPPATH\Controllers\UsuarioController.php(22): App\Models\UsuarioModel->obtener([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->login()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-25 00:12:52 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'localhost' in C:\xampp\htdocs\presupuesto\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\presupuesto\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'localhost', 3306, '', 0)
#1 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\presupuesto\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\presupuesto\system\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\presupuesto\app\Models\UsuarioModel.php(29): CodeIgniter\Model->__call('get', Array)
#6 C:\xampp\htdocs\presupuesto\app\Controllers\UsuarioController.php(22): App\Models\UsuarioModel->obtener(Array)
#7 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(933): App\Controllers\UsuarioController->login()
#8 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#9 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\presupuesto\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\presupuesto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\presupuesto\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'localhost' in C:\xampp\htdocs\presupuesto\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\presupuesto\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\presupuesto\system\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\presupuesto\app\Models\UsuarioModel.php(29): CodeIgniter\Model->__call('get', Array)
#5 C:\xampp\htdocs\presupuesto\app\Controllers\UsuarioController.php(22): App\Models\UsuarioModel->obtener(Array)
#6 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(933): App\Controllers\UsuarioController->login()
#7 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#8 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\presupuesto\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\presupuesto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\presupuesto\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-08-25 00:12:52 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'localhost'
[Method: POST, Route: loguear]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuario`
WHERE `email` = :email:', [...], false)
 3 SYSTEMPATH\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Models\UsuarioModel.php(29): CodeIgniter\Model->__call('get', [])
 5 APPPATH\Controllers\UsuarioController.php(22): App\Models\UsuarioModel->obtener([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->login()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-25 00:20:21 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'localhost' in C:\xampp\htdocs\presupuesto\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\presupuesto\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'localhost', 3306, '', 0)
#1 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\presupuesto\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\presupuesto\app\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\presupuesto\app\Controllers\UsuarioController.php(64): App\Models\UsuarioModel->insertar(Array)
#6 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
#7 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#8 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\presupuesto\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\presupuesto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\presupuesto\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'localhost' in C:\xampp\htdocs\presupuesto\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\presupuesto\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\presupuesto\app\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert(Array)
#4 C:\xampp\htdocs\presupuesto\app\Controllers\UsuarioController.php(64): App\Models\UsuarioModel->insertar(Array)
#5 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
#6 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#7 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\presupuesto\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\presupuesto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\presupuesto\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-08-25 00:20:21 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'localhost'
[Method: POST, Route: guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuario` (`nombre`, `apellido`, `telefono`, `email`, `password`, `status`) VALUES (:nombre:, :apellido:, :telefono:, :email:, :password:, :status:)', [...], false)
 3 APPPATH\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert([...])
 4 APPPATH\Controllers\UsuarioController.php(64): App\Models\UsuarioModel->insertar([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-25 00:24:20 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'localhost' in C:\xampp\htdocs\presupuesto\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\presupuesto\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'localhost', 3306, '', 0)
#1 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\presupuesto\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\presupuesto\app\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\presupuesto\app\Controllers\UsuarioController.php(64): App\Models\UsuarioModel->insertar(Array)
#6 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
#7 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#8 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\presupuesto\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\presupuesto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\presupuesto\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'localhost' in C:\xampp\htdocs\presupuesto\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\presupuesto\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\presupuesto\app\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert(Array)
#4 C:\xampp\htdocs\presupuesto\app\Controllers\UsuarioController.php(64): App\Models\UsuarioModel->insertar(Array)
#5 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
#6 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#7 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\presupuesto\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\presupuesto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\presupuesto\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-08-25 00:24:20 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'localhost'
[Method: POST, Route: guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuario` (`nombre`, `apellido`, `telefono`, `email`, `password`, `status`) VALUES (:nombre:, :apellido:, :telefono:, :email:, :password:, :status:)', [...], false)
 3 APPPATH\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert([...])
 4 APPPATH\Controllers\UsuarioController.php(64): App\Models\UsuarioModel->insertar([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-25 00:24:39 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'localhost' in C:\xampp\htdocs\presupuesto\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\presupuesto\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'localhost', 3306, '', 0)
#1 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\presupuesto\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\presupuesto\app\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert(Array)
#5 C:\xampp\htdocs\presupuesto\app\Controllers\UsuarioController.php(64): App\Models\UsuarioModel->insertar(Array)
#6 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
#7 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#8 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\presupuesto\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\presupuesto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\presupuesto\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'localhost' in C:\xampp\htdocs\presupuesto\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\presupuesto\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 C:\xampp\htdocs\presupuesto\app\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert(Array)
#4 C:\xampp\htdocs\presupuesto\app\Controllers\UsuarioController.php(64): App\Models\UsuarioModel->insertar(Array)
#5 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
#6 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#7 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\presupuesto\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\presupuesto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#10 C:\xampp\htdocs\presupuesto\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#11 {main}
CRITICAL - 2024-08-25 00:24:39 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'localhost'
[Method: POST, Route: guardar]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `usuario` (`nombre`, `apellido`, `telefono`, `email`, `password`, `status`) VALUES (:nombre:, :apellido:, :telefono:, :email:, :password:, :status:)', [...], false)
 3 APPPATH\Models\UsuarioModel.php(34): CodeIgniter\Database\BaseBuilder->insert([...])
 4 APPPATH\Controllers\UsuarioController.php(64): App\Models\UsuarioModel->insertar([...])
 5 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
 6 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 7 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
10 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-08-25 00:25:57 --> ErrorException: Undefined variable $request
[Method: POST, Route: guardar]
in APPPATH\Controllers\UsuarioController.php on line 49.
 1 APPPATH\Controllers\UsuarioController.php(49): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $request', 'C:\\xampp\\htdocs\\presupuesto\\app\\Controllers\\UsuarioController.php', 49)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-08-25 00:25:59 --> ErrorException: Undefined variable $request
[Method: POST, Route: guardar]
in APPPATH\Controllers\UsuarioController.php on line 49.
 1 APPPATH\Controllers\UsuarioController.php(49): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $request', 'C:\\xampp\\htdocs\\presupuesto\\app\\Controllers\\UsuarioController.php', 49)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-08-25 00:26:14 --> ErrorException: Undefined variable $request
[Method: POST, Route: guardar]
in APPPATH\Controllers\UsuarioController.php on line 49.
 1 APPPATH\Controllers\UsuarioController.php(49): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $request', 'C:\\xampp\\htdocs\\presupuesto\\app\\Controllers\\UsuarioController.php', 49)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
ERROR - 2024-08-25 00:27:20 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'localhost' in C:\xampp\htdocs\presupuesto\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 C:\xampp\htdocs\presupuesto\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'localhost', 3306, '', 0)
#1 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\presupuesto\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\presupuesto\system\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\presupuesto\app\Models\UsuarioModel.php(29): CodeIgniter\Model->__call('get', Array)
#6 C:\xampp\htdocs\presupuesto\app\Controllers\UsuarioController.php(22): App\Models\UsuarioModel->obtener(Array)
#7 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(933): App\Controllers\UsuarioController->login()
#8 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#9 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\xampp\htdocs\presupuesto\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 C:\xampp\htdocs\presupuesto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 C:\xampp\htdocs\presupuesto\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'localhost' in C:\xampp\htdocs\presupuesto\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\presupuesto\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\presupuesto\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\presupuesto\system\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\presupuesto\app\Models\UsuarioModel.php(29): CodeIgniter\Model->__call('get', Array)
#5 C:\xampp\htdocs\presupuesto\app\Controllers\UsuarioController.php(22): App\Models\UsuarioModel->obtener(Array)
#6 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(933): App\Controllers\UsuarioController->login()
#7 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
#8 C:\xampp\htdocs\presupuesto\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\presupuesto\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\presupuesto\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 C:\xampp\htdocs\presupuesto\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 {main}
CRITICAL - 2024-08-25 00:27:20 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Unknown database 'localhost'
[Method: POST, Route: loguear]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `usuario`
WHERE `email` = :email:', [...], false)
 3 SYSTEMPATH\Model.php(930): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Models\UsuarioModel.php(29): CodeIgniter\Model->__call('get', [])
 5 APPPATH\Controllers\UsuarioController.php(22): App\Models\UsuarioModel->obtener([...])
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->login()
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-08-25 00:32:39 --> ErrorException: Undefined variable $request
[Method: POST, Route: guardar]
in APPPATH\Controllers\UsuarioController.php on line 49.
 1 APPPATH\Controllers\UsuarioController.php(49): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Undefined variable $request', 'C:\\xampp\\htdocs\\presupuesto\\app\\Controllers\\UsuarioController.php', 49)
 2 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\UsuarioController->create()
 3 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\UsuarioController))
 4 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 5 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
 6 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 7 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
